[package]
name = "pion-experiments"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.3.2"
contracts = "0.6.3"
rpds = "0.12.0"
text-size = "1.1.0"
